---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
require(httr)
library(jsonlite)
library(digest)
library(dplyr)

# GET TOKEN

browseURL("http://www.last.fm/api/auth/?api_key=aeeeca3484217e70ed731b0e26290c0c")
token <- "5WLHnDql76FfV-cgmEAEuEaiB8w45ENN" #paste token from korelskk.ru url here

```

```{r}
# GET TOP TRACKS
# documentation - https://www.last.fm/api/show/chart.getTopTracks

tracks <- data.frame()

for (i in 1:200) { #change nums here
  urlTopTracks <- gsub(" ", "", paste("http://ws.audioscrobbler.com/2.0/?method=chart.getTopTracks&api_key=aeeeca3484217e70ed731b0e26290c0c&page=", i, "perPage=200&format=json"))
  topTracks <- jsonlite::fromJSON(urlTopTracks)
  topTracks <- as.data.frame(topTracks) 
  
  topTracks$artist.name <- topTracks$tracks.track.artist$name
  topTracks$artist.mbid <- topTracks$tracks.track.artist$mbid
  topTracks$artist.url <- topTracks$tracks.track.artist$url
  topTracks <- topTracks[, c(1, 2, 4, 10, 11, 12, 13, 14, 15, 16)]

  tracks <- bind_rows(tracks, topTracks)
}

saveRDS(tracks, "data/tracks_101-500.rds") # change nums here (same as in 32)
```

```{r}
# TOP TRACKS WITH TAGS

tracksWithTags <- tracks
tracksWithTags$tags <- 0
tracksWithTags$tagsCount<- 0

for (i in 1:nrow(tracksWithTags)) { #change nums here
  urlWithTags <- gsub("= ", "=", paste("http://ws.audioscrobbler.com/2.0/?method=track.getTopTags&api_key=aeeeca3484217e70ed731b0e26290c0c&artist=", tracksWithTags$artist.name[i], "&track=", tracksWithTags$tracks.track.name[i], "&format=json"))
  urlWithTags <- gsub(" &", "&", urlWithTags)

  tags <- try(jsonlite::fromJSON(URLencode(urlWithTags)))
  
  if (class(tags) != "try-error") {
    if (!is.null(tags$toptags$tag$name)) {
      tags <- as.data.frame(tags)
      tracksWithTags$tags[i] <- list(tags$toptags.tag.name)
      tracksWithTags$tagsCount[i] <- list(tags$toptags.tag.count)
    }
  }  
}

saveRDS(tracksWithTags, "data/tracksWithTags_101-200.rds") # same nums as in 55
```

```{r}
# GET TOP TRACKS WITH TAG 'RUSSIAN'
# documentation - https://www.last.fm/api/show/tag.getTopTracks

tracksRussian <- data.frame()

for (i in 1:5) { #change nums here
  urlTopTracks <- gsub(" ", "", paste("http://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks&tag=russian&api_key=aeeeca3484217e70ed731b0e26290c0c&page=", i, "perPage=200&format=json"))
  topTracks <- jsonlite::fromJSON(urlTopTracks)
  topTracks <- as.data.frame(topTracks) 
  
  topTracks$artist.name <- topTracks$tracks.track.artist$name
  topTracks$artist.mbid <- topTracks$tracks.track.artist$mbid
  topTracks$artist.url <- topTracks$tracks.track.artist$url
  topTracks <- topTracks[, c(1, 2, 4, 10, 11, 12, 13, 14, 15, 16)]

  tracksRussian <- bind_rows(tracksRussian, topTracks)
}

saveRDS(tracksRussian, "data/tracks_russian_1-200.rds") # change nums here (same as in 72)
```